name: Release Please
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: "takip-kira-panel"
          bump-minor-pre-major: true
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
